.TH "HIPGISAXS" "1" "08/28/2012" "" "Simulation Tools"
.nh
.ad l
.SH "NAME"
hipgisaxs \- High Performance GISAXS (Grazing Incidence Small Angle X-ray Scattering) simulation tool
.SH "SYNOPSIS"
.HP 6
\fBhipgisaxs\fR [OPTION] HiG-INPUT-FILE
.SH "DESCRIPTION"
This is a high-performance tool which can take advantage of GPUs, multi-core CPUs and their clusters. Something something will come here.
.SH "OPTIONS"
None yet. If any come up in future versions, they will be listed here.
.SH "ENVIRONMENT"
List of environment variables affecting hipgisaxs execution.
.SH "EXAMPLES"
Some examples will be listed here.
.SH "HiG INPUT FORMAT"
Description of the input file format.
.SH "HiG INPUT EXAMPLES"
Some examples of the input files.
.SH "COMPATIBILITY"
This code is not compatible with standards lower than C++0x/C++11. It is also not compatible with CUDA versions lower than 4.0. This code has only been tested with the OpenMPI implementation of MPI-2.
.SH "STANDARDS"
This tool conforms to C++11 standard.
.SH "DOCUMENTATION"
A complete documentation can be found in the doc directory included with this package. It can also be found at \fIhttp://www.lbl.gov/hipgisaxs/userguide.html\fR.
.SH "AUTHOR"
This \fIHipGISAXS\fR package based on C++, NVIDIA CUDA, OpenMP, MPI and parallel-HDF5 was written by Abhinav Sarje. HiG input format was developed by Abhinav Sarje, Slim T. Chourou and Elaine R. Chan.
.SH "DEVELOPERS"
HipGISAXS was developed by Slim T. Chourou, Abhinav Sarje, Elaine R. Chan, Alexander Hexemer and Xiaoye S. Li at the Lawrence Berkeley National Laboratory, Berkeley, USA.
.SH "HISTORY"
HipGISAXS was preceeded by a sequential MATLAB implementation written by Slim T. Chourou as a proof of concept.
.SH "KNOWN BUGS"
A list of known bugs which are being worked upon.
.SH "REPORTING BUGS"
Found a bug? Report any bugs which are not listed above to \fIbugs-hipgisaxs@lbl.gov\fR with detailed information about the case(s) when the bug(s) manifested.
.SH "LICENSING AND COPYRIGHT"
Here will be the licensing and copyright information.
.SH "SEE ALSO"
Anything to see also?
