Import('env')

objs = [ ]
sources = ['utilities.cpp', 'string_utils.cpp', 'matmul.cpp']
objs += env.Object(sources)

Export('env')
using_accelerator = env['ACCELERATOR_TYPE']
if using_accelerator == 'gpu':
	objs += SConscript('gpu/SConscript')
elif using_accelerator == 'mic':
	objs += SConscript('mic/SConscript')
else:
	objs += SConscript('cpu/SConscript')

Return('objs')
