Import('env')

objs = [ ]
sources = ['read_oo_input.cpp', 'objectshape_reader.cpp']
objs += env.Object(sources)

h5sources = ['hdf5shape_reader.c']
h5env = env.Clone(CC = 'h5pcc -c')		## a hack
objs += h5env.Object(h5sources)

Return('objs')

