Import('env')

objs = [ ]
sources = ['hipgisaxs_main.cpp', 'hipgisaxs_helpers.cpp']
objs += env.Object(sources)

main_sources = ['hipgisaxs_sim.cpp']
main_obj = env.Object(main_sources)

Return('objs', 'main_obj')
